### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by archon5880** [cryptapus/electrum-uno#1]
Unobtainium Electrum wallet 2.6.2 (recommended for newcomers) is not synchronizing past 9 July 2017.  Under Network, there are only 3 servers:
kraken.cryptap.us
electrum1.unobtanium.uno
kraken.cryptap.us
Should there be more?

**Comment by archon5880** [comment]
I just tried and it has properly synced through today.  It does not matter which of the 3 servers I select, or have automatically selected.  They all work.  Thanks.

**Comment by cryptapus** [comment]
this software is no longer maintained by me

https://github.com/cryptapus/electrum-uno
