### ISSUE TITLE
Unobtanium Electrum 2.6.2. Wallet not syncing

### ISSUE THREAD

**Issue by 4speedy** [cryptapus/electrum-uno#2]
I have Norton Security. I've had my Unobtanium Electrum 2.6.2. wallet since about October 1. I tried using the Kraken server primarily. However, none have worked consistently. The only time I got the wallet in sync enough to send something, I used the unobtanium1 server and turned off the ssl. I use no proxies. Why is it so difficult to sync the wallet so it can be functional. I started with only 2 or 3 servers; now I'm getting up to 6 or 7, including two Nigerian servers and 2 or 3 numbers-only servers. I'd like to use one I could trust and which I could make sync and usable. What steps should I take.

**Comment by cryptapus** [comment]
This software is no longer maintained by me

https://github.com/cryptapus/electrum-uno
